feat: integrate cex on-ramp cede.store widget
Polkadex-Substrate/Polkadex-Orderbook-Frontend pull request #1208
Opened 2024-04-24 17:29 UTC by neeeekitos

## Description
Following our discussion regarding the CEX On-Ramp widget integration with cede.store, I integrate the cede.store widget allowing to transfer funds from centralized exchanges to a wallet connetected to Polkadex.

## Changes Made

Added a widget page
<img width="1512" alt="image" src="https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/assets/57397713/1ec383fd-d9c7-423b-8df4-0c7eec78d72d">

Added a sidebar link to on-ramp widget page:
<img width="476" alt="image" src="https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/assets/57397713/190f6dd7-6cde-42f4-bfbc-bac77cca7ecd">

Added an on-ramp link to the modal:
<img width="384" alt="image" src="https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/assets/57397713/ec3113a1-db34-41f3-a382-1998da971cce">

## How to Test

Check this page: http://localhost:3000/cexOnRamp
You can downoad cede.store extension, add a cex and try to withdraw. If you don't want to import your API keys or don't have a CEX account, you can use the extension in the demo mode to check the withdrawal.

## Checklist

- [ ] Included link to corresponding [Polkadex Orderbook Frontend Issue](https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/issues).
- [ ] I have tested these changes thoroughly.
- [ ] I have requested a review from at least one other contributor.

2024-04-25 14:16 UTC, nuel77 commented
hey @neeeekitos thanks for the contirbution. we will check this and added it along with the next weekly release.

2024-04-26 02:59 UTC, ap211unitech requested changes

2024-04-26 02:59 UTC, ap211unitech commented on apps/hestia/src/components/cexOnRamp/template.tsx
> +import { Help } from "../transfer/Help";
We are using component based project structure so all the components required for a page, should be in current folder only. 

For e.g. You can't import `Help` component from transfer page. I would suggest you to create a Help component in current directory.

2024-04-26 02:59 UTC, ap211unitech commented on apps/hestia/src/components/cexOnRamp/template.tsx
> +import { SelectAsset } from "../transfer/SelectAsset";
Same here

2024-04-26 02:59 UTC, ap211unitech commented on apps/hestia/src/app/cexOnRamp/layout.tsx
> +  return <WithdrawsProvider>{children}</WithdrawsProvider>;
I don't think `WithdrawProvider` is required here. Can you remove it ?

2024-04-26 02:59 UTC, ap211unitech commented on apps/hestia/src/app/cexOnRamp/layout.tsx
> +  return <WithdrawsProvider>{children}</WithdrawsProvider>;
You can rather delete this file, there would be no different layout required here. We already have a layout file in `app` folder.

2024-04-26 02:59 UTC, ap211unitech commented on apps/hestia/src/components/cexOnRamp/template.tsx
> +        accentColor: themeConfig.theme.extend.colors["primary-base"],
Please refactor it a bit with a variable. 

```js
const extend = themeConfig.theme.extend; // Define it outside the component.
```

and use it like this.

```js
borderColor: extend.colors["secondary-base"]
```

Check [this](https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/blob/release/apps/hestia/src/components/trading/Graph/config.ts#L11) out for help.

2024-04-26 06:14 UTC, neeeekitos commented
Hey @ap211unitech, thank you for your review. I've implemented the required fixes and cleaned up the `cexOnRamp` page

2024-04-26 07:03 UTC, ap211unitech requested changes
<img width="1920" alt="image" src="https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/assets/65214523/e5da2472-aeb6-4e41-87cf-7aa577bbf7cf">

The  `#cede.widget` component doesn't look properly aligned. It's not properly vertically aligned.

2024-04-26 07:03 UTC, ap211unitech commented on apps/hestia/src/components/cexOnRamp/template.tsx
> +  }, []);
Missing dependency values here.

2024-04-26 07:03 UTC, ap211unitech commented on apps/hestia/src/components/cexOnRamp/template.tsx
> +        borderRadius: -15,
Border radius in negative ? Doesn't make sense.

2024-04-26 07:03 UTC, ap211unitech commented on apps/hestia/src/components/cexOnRamp/template.tsx
> +        borderRadius: -15,
Put 1 instead

2024-04-26 07:52 UTC, neeeekitos commented
@ap211unitech done ✅

2024-04-26 10:23 UTC, ap211unitech approved these changes

2024-04-26 10:24 UTC, ap211unitech commented
@neeeekitos Great. Approved it.

2024-04-28 15:16 UTC, minikas approved these changes

2024-04-28 16:04 UTC, merged