Implement Backup Functionality for Trading Account on Google Drive
Polkadex-Substrate/Polkadex-Orderbook-Frontend pull request #1210
Opened 2024-04-25 10:44 UTC by minikas

## Description

## Changes Made

This pull request introduces the integration of Google Drive backup functionality for trading accounts within Orderbook. The aim is to provide users with a seamless experience for securely storing and retrieving their trading data using Google Drive.

Changes Made:

- [x] feat: Implemented integration with the Google Drive API to enable communication between Orderbook and Google Drive.
- [x] feat: Implemented automatic backup functionality when users create a new trading account. 
- [x] feat: Enabled users to backup any trading accounts stored in local storage to Google Drive.
- [x] feat: Implemented the option for users to remove trading accounts stored in Google Drive directly from within the Orderbook interface.
- [ ] feat: Implemented the option for users to move the trading accounts stored in the Google Drive to localstorage directly from within the Orderbook interface.
- [x] fix: Remove QuickStart component of all pages

## Screenshots / Screencasts
https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/assets/12574469/c730402e-65c4-4532-bc9a-b68774e5d547

## Checklist

- [ ] Included link to corresponding [Polkadex Orderbook Frontend Issue](https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/issues).
- [ ] I have tested these changes thoroughly.
- [ ] I have requested a review from at least one other contributor.

Close: https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/issues/1201

2024-04-29 17:34 UTC, nuel77 approved these changes

2024-04-30 05:25 UTC, ap211unitech requested changes

2024-04-30 05:25 UTC, ap211unitech commented on packages/core/src/providers/user/connectWalletProvider/index.tsx
> +  } = useMutation({
I think `useMutation` and `useQuery` shouldn't be called here directly. We should rather create a new folder `core/hooks/gDrive` and put all gDrive related stuff there. Please define all related hooks there.

2024-04-30 05:25 UTC, ap211unitech commented on packages/core/src/providers/user/connectWalletProvider/index.tsx
> +  } = useMutation({
You can import hooks from there and use them here.

2024-05-01 03:04 UTC, ap211unitech approved these changes

2024-05-01 11:09 UTC, merged