Refactor Cross Chain Logic
Polkadex-Substrate/Polkadex-Orderbook-Frontend pull request #1281
Opened 2024-05-22 04:50 UTC by ap211unitech

## Description

## Changes Made

## How to Test

## Screenshots / Screencasts

## Checklist

- [x] Included link to corresponding [Polkadex Orderbook Frontend Issue](https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/issues).
- [ ] I have tested these changes thoroughly.
- [ ] I have requested a review from at least one other contributor.

2024-05-22 11:04 UTC, minikas requested changes
- There is a problem with the validations.
- The max button is no longer visible

https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/assets/12574469/550c460d-f959-4556-8e0e-4b164d998da5

2024-05-23 09:01 UTC, ap211unitech commented
> * There is a problem with the validations.
> * The max button is no longer visible
> 
>  Screen.Recording.2024-05-22.at.07.57.03.mov

@minikas This is fixed now. Please review again.

2024-05-23 11:11 UTC, minikas requested changes

2024-05-23 11:11 UTC, minikas commented on apps/hestia/src/components/thea/Help/index.tsx
> +      <Card
Make the entire component clickable

2024-05-23 11:11 UTC, minikas requested changes

2024-05-23 11:11 UTC, minikas commented on apps/hestia/src/components/thea/Help/index.tsx
> +      <Card
Same here

2024-05-23 11:17 UTC, minikas requested changes
Check the alignment
![Screenshot 2024-05-23 at 08 13 17](https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/assets/12574469/15890fc6-1075-43ee-925e-352a04d3d262)

2024-05-23 11:26 UTC, minikas requested changes

2024-05-23 11:26 UTC, minikas commented on apps/hestia/src/components/thea/Help/index.tsx
> +      <Card
Increase the size of the title

2024-05-23 11:40 UTC, ap211unitech commented on apps/hestia/src/components/thea/Help/index.tsx
> +      <Card
Done

2024-05-23 11:40 UTC, ap211unitech commented on apps/hestia/src/components/thea/Help/index.tsx
> +      <Card
Done

2024-05-23 11:42 UTC, ap211unitech commented
> Check the alignment ![Screenshot 2024-05-23 at 08 13 17](https://private-user-images.githubusercontent.com/12574469/333160801-15890fc6-1075-43ee-925e-352a04d3d262.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NjQ3NzUsIm5iZiI6MTcxNjQ2NDQ3NSwicGF0aCI6Ii8xMjU3NDQ2OS8zMzMxNjA4MDEtMTU4OTBmYzYtMTA3NS00M2VlLTkyNWUtMzUyYTA0ZDNkMjYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDExNDExNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyMmZlZWY5M2E2OTViMGU0YWViMzNhOGM1ZjI5MWUyNjBkMGM4ODYyNmE1NmE0YmJkZjZlNmQzMTI2NWIzNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.u4UPLirfVze_Gere_Qr-71Z9gn-Y3V8GCzhI3NHIW8A)

@minikas This is fixed now.

2024-05-23 11:53 UTC, minikas approved these changes
LGTM

2024-05-23 13:21 UTC, nuel77 approved these changes

2024-05-23 13:21 UTC, merged